-- seed_articles_workshops.sql — generated from src/lib/data/mocks.ts
-- Jalankan di SQL Editor (bypass RLS). Idempotent via ON CONFLICT slug.

-- 12 articles (pakai category slug lookup)
insert into articles (category_id, title, slug, excerpt, content, cover_url, published) values ((select id from categories where slug='oli'), 'Kapan Harus Ganti Oli? Panduan 2.000km untuk Motor Harian', 'kapan-ganti-oli', 'Jangan tunggu oli hitam pekat. Kenali tanda oli minta ganti dan risiko telat ganti oli.', 'Oli adalah darah motor. Untuk pemakaian harian Surabaya (macet + panas), ganti tiap 2000km atau 2 bulan. Cek warna, kekentalan, dan suara mesin. Telat ganti = mesin cepat panas, tarikan berat, dan keausan komponen.', 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&q=80', true) on conflict (slug) do nothing;
insert into articles (category_id, title, slug, excerpt, content, cover_url, published) values ((select id from categories where slug='rem'), 'Rem Berdecit? Ini Penyebab dan Cara Mengatasinya', 'rem-berdecit', 'Rem bunyi bukan sepele. Bisa kampas habis atau piringan kotor.', 'Cek kampas rem tiap 5000km. Jika berdecit, bersihkan piringan, cek ketebalan kampas, dan pastikan minyak rem cukup. Jangan rem mendadak saat kampas tipis.', 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=800&q=80', true) on conflict (slug) do nothing;
insert into articles (category_id, title, slug, excerpt, content, cover_url, published) values ((select id from categories where slug='ban'), 'Tekanan Angin Ban Ideal: Nyaman, Irit, Anti Selip', 'tekanan-ban-ideal', 'Ban kempes bikin boros bensin dan licin saat hujan.', 'Cek tekanan tiap 1 minggu. Depan 29-33 psi, belakang 33-36 psi tergantung beban. Ban botak = ganti, jangan ditambal terus.', 'https://images.unsplash.com/photo-1558980664-2506f92884c5?w=800&q=80', true) on conflict (slug) do nothing;
insert into articles (category_id, title, slug, excerpt, content, cover_url, published) values ((select id from categories where slug='cvt'), 'Servis CVT Matic: Biar Tarikan Enteng Tiap 8.000km', 'servis-cvt-matic', 'CVT kotor bikin gredek dan boros.', 'Bongkar CVT, bersihkan roller, vanbelt, kampas ganda. Ganti vanbelt tiap 20.000km. Jangan lupa cek grease.', 'https://images.unsplash.com/photo-1449426468159-d96dbf08f19f?w=800&q=80', true) on conflict (slug) do nothing;
insert into articles (category_id, title, slug, excerpt, content, cover_url, published) values ((select id from categories where slug='aki'), 'Aki Soak? Kenali Tanda Sebelum Motor Mogok', 'aki-soak', 'Starter lemah dan lampu redup adalah sinyal aki minta perhatian.', 'Aki kering tahan 1.5-2 tahun. Cek voltase 12.4V+, bersihkan terminal, jangan biarkan motor lama tidak dinyalakan.', 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80', true) on conflict (slug) do nothing;
insert into articles (category_id, title, slug, excerpt, content, cover_url, published) values ((select id from categories where slug='rantai'), 'Rantai Kendor Bikin Berisik? Setel Tiap 3.000km', 'rantai-kendor', 'Rantai kendor bikin tenaga hilang dan boros gear.', 'Setel kekencangan 20-30mm, lumasi tiap 500km, ganti gir set jika sudah tajam.', 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800&q=80', true) on conflict (slug) do nothing;
insert into articles (category_id, title, slug, excerpt, content, cover_url, published) values ((select id from categories where slug='tips'), '5 Kebiasaan Bikin Motor Awet 10 Tahun', 'kebiasaan-motor-awet', 'Panaskan mesin 1 menit, jangan geber saat dingin, rutin cek oli.', 'Kebiasaan kecil berdampak besar. Servis berkala, cuci motor jangan semprot CVT langsung, parkir teduh.', 'https://images.unsplash.com/photo-1504215680853-026ed2a45def?w=800&q=80', true) on conflict (slug) do nothing;
insert into articles (category_id, title, slug, excerpt, content, cover_url, published) values ((select id from categories where slug='pengetahuan'), 'Mengenal Komponen Motor: Dari CVT Hingga ECU', 'mengenal-komponen-motor', 'Paham istilah bengkel biar tidak bingung saat servis.', 'CVT = transmisi matic, ECU = otak injeksi, TB = throttle body. Paham dasar bikin tidak mudah ditipu.', 'https://images.unsplash.com/photo-1511919884226-fd3ec7956e9d?w=800&q=80', true) on conflict (slug) do nothing;
insert into articles (category_id, title, slug, excerpt, content, cover_url, published) values ((select id from categories where slug='faq'), 'FAQ: Berapa Biaya Servis Rutin Motor Matic?', 'faq-biaya-servis', 'Estimasi biaya servis ringan 150-300rb tergantung bengkel dan sparepart.', 'Servis ringan: oli + CVT bersih + cek rem. Servis berat: + ganti vanbelt + kampas + aki. Selalu minta rincian.', 'https://images.unsplash.com/photo-1521119989659-a83eee488004?w=800&q=80', true) on conflict (slug) do nothing;
insert into articles (category_id, title, slug, excerpt, content, cover_url, published) values ((select id from categories where slug='mesin'), 'Mesin Overheat di Macet Surabaya? Ini Solusinya', 'mesin-overheat', 'Radiator, oli, dan air coolant adalah kunci.', 'Jangan paksa jalan saat overheat. Menepi, matikan mesin 15 menit, cek coolant dan oli. Jika sering, cek thermostat.', 'https://images.unsplash.com/photo-1609630875170-59d7a3865ca9?w=800&q=80', true) on conflict (slug) do nothing;
insert into articles (category_id, title, slug, excerpt, content, cover_url, published) values ((select id from categories where slug='kelistrikan'), 'Lampu Sering Putus? Cek Kiprok dan Aki', 'lampu-sering-putus', 'Kelistrikan tidak stabil merusak lampu dan ECU.', 'Cek kiprok/regulator, sekring, dan kabel. Ganti bohlam sesuai watt, jangan asal terang.', 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80', true) on conflict (slug) do nothing;
insert into articles (category_id, title, slug, excerpt, content, cover_url, published) values ((select id from categories where slug='oli'), 'Oli Matic vs Manual: Jangan Salah Tuang', 'oli-matic-vs-manual', 'SAE dan JASO berbeda, salah oli bikin selip kopling.', 'Matic pakai JASO MB, manual pakai JASO MA. Cek SAE 10W-30 vs 10W-40 sesuai buku manual. Untuk katalog lengkap dengan harga bengkel, buka menu OLI.', 'https://images.unsplash.com/photo-1647427060118-4911c9821b82?w=800&q=80', true) on conflict (slug) do nothing;

-- 12 workshops (3 sudah ada, ON CONFLICT akan skip)
insert into workshops (name, slug, address, kecamatan, lat, lng, jam_operasional, layanan, kontak, foto_url, rating) values ('Bengkel AHASS Surya Agung', 'ahass-surya-agung', 'Jl. Ahmad Yani No. 12, Wonokromo', 'Wonokromo', -7.2975, 112.738, '08:00-17:00', array['Bengkel','Servis Berkala','Ganti Oli'], '031-8281234', 'https://images.unsplash.com/photo-1613214149922-f1809c99b414?w=600&q=80', 4.7) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, lat, lng, jam_operasional, layanan, kontak, foto_url, rating) values ('Tambal Ban 24 Jam Darmo', 'tambal-ban-darmo', 'Jl. Raya Darmo No. 88', 'Wonokromo', -7.284, 112.737, '24 Jam', array['Tambal Ban','Tubles'], '0812-3456-7890', 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600&q=80', 4.5) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, lat, lng, jam_operasional, layanan, kontak, foto_url, rating) values ('Cuci Motor Kinclong Gubeng', 'cuci-motor-gubeng', 'Jl. Gubeng Pojok No. 5', 'Gubeng', -7.265, 112.75, '07:00-21:00', array['Cuci Motor','Detailing'], '0813-1111-2222', 'https://images.unsplash.com/photo-1521119989659-a83eee488004?w=600&q=80', 4.8) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, lat, lng, jam_operasional, layanan, kontak, foto_url, rating) values ('Bengkel Jaya Motor Rungkut', 'jaya-motor-rungkut', 'Jl. Rungkut Industri No. 3', 'Rungkut', -7.33, 112.77, '08:00-18:00', array['Bengkel','CVT','Rem'], '031-8701234', 'https://images.unsplash.com/photo-1613214149922-f1809c99b414?w=600&q=80', 4.6) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, lat, lng, jam_operasional, layanan, kontak, foto_url, rating) values ('Planet Ban Sukolilo', 'planet-ban-sukolilo', 'Jl. Arief Rahman Hakim No. 14', 'Sukolilo', -7.29, 112.785, '08:00-20:00', array['Ban','Tambal Ban','Ganti Ban'], '031-5912345', 'https://images.unsplash.com/photo-1558980664-2506f92884c5?w=600&q=80', 4.4) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, lat, lng, jam_operasional, layanan, kontak, foto_url, rating) values ('AHASS Tenggilis Mejoyo', 'ahass-tenggilis', 'Jl. Tenggilis No. 22', 'Tenggilis Mejoyo', -7.315, 112.76, '08:00-17:00', array['Bengkel','Servis Berkala'], '031-8412345', 'https://images.unsplash.com/photo-1613214149922-f1809c99b414?w=600&q=80', 4.6) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, lat, lng, jam_operasional, layanan, kontak, foto_url, rating) values ('Cuci Steam Benowo', 'cuci-steam-benowo', 'Jl. Benowo No. 9', 'Benowo', -7.235, 112.65, '07:00-22:00', array['Cuci Motor','Cuci Steam'], '0812-9999-8888', 'https://images.unsplash.com/photo-1521119989659-a83eee488004?w=600&q=80', 4.3) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, lat, lng, jam_operasional, layanan, kontak, foto_url, rating) values ('Bengkel Sumber Rejeki Kenjeran', 'sumber-rejeki-kenjeran', 'Jl. Kenjeran No. 77', 'Kenjeran', -7.22, 112.78, '08:00-19:00', array['Bengkel','Kelistrikan','Aki'], '031-3891234', 'https://images.unsplash.com/photo-1613214149922-f1809c99b414?w=600&q=80', 4.5) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, lat, lng, jam_operasional, layanan, kontak, foto_url, rating) values ('Tambal Ban Pak Kumis Wonocolo', 'tambal-ban-wonocolo', 'Jl. Wonocolo No. 15', 'Wonocolo', -7.32, 112.735, '06:00-22:00', array['Tambal Ban'], '0813-7777-6666', 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600&q=80', 4.2) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, lat, lng, jam_operasional, layanan, kontak, foto_url, rating) values ('Bengkel Matic Specialist Dukuh Pakis', 'matic-dukuh-pakis', 'Jl. Dukuh Pakis No. 33', 'Dukuh Pakis', -7.28, 112.715, '09:00-18:00', array['Bengkel','CVT','Servis Matic'], '031-7321234', 'https://images.unsplash.com/photo-1613214149922-f1809c99b414?w=600&q=80', 4.9) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, lat, lng, jam_operasional, layanan, kontak, foto_url, rating) values ('Cuci Motor Express Citraland', 'cuci-citraland', 'Jl. Citraland No. 1', 'Lakarsantri', -7.295, 112.625, '07:00-21:00', array['Cuci Motor','Detailing','Coating'], '0812-3333-4444', 'https://images.unsplash.com/photo-1521119989659-a83eee488004?w=600&q=80', 4.7) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, lat, lng, jam_operasional, layanan, kontak, foto_url, rating) values ('Bengkel 88 Gunung Anyar', 'bengkel-88-gunung-anyar', 'Jl. Gunung Anyar No. 45', 'Gunung Anyar', -7.335, 112.79, '08:00-17:00', array['Bengkel','Ganti Oli','Servis Berkala'], '031-8723456', 'https://images.unsplash.com/photo-1613214149922-f1809c99b414?w=600&q=80', 4.4) on conflict (slug) do nothing;

select 'articles' as tbl, count(*) from articles union all select 'workshops', count(*) from workshops;
