-- seed_motor_specs_100.sql -- 100 spek dari database_spek_motor_motorkita_100.xlsx
-- Buat tabel motor_specs jika belum ada (dipakai halaman admin Spek Motor + Motor Saya).

create table if not exists motor_specs (
  id uuid primary key default gen_random_uuid(),
  brand text not null,
  model text not null,
  type text check (type in ('matic','manual','kopling')) not null default 'matic',
  oli text,
  volume_oli text,
  ban_depan text,
  ban_belakang text,
  aki text,
  busi text,
  catatan text,
  created_at timestamptz default now(),
  unique (brand, model)
);
alter table motor_specs enable row level security;
drop policy if exists "public read specs" on motor_specs;
create policy "public read specs" on motor_specs for select using (true);
drop policy if exists "admin write specs" on motor_specs;
create policy "admin write specs" on motor_specs for all using (
  exists (select 1 from profiles where profiles.id = auth.uid() and profiles.role = 'admin')
) with check (
  exists (select 1 from profiles where profiles.id = auth.uid() and profiles.role = 'admin')
);

insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'BeAT', 'matic', '10W-30 JASO MB', '0.65 L', '80/90-14', '90/90-14', 'MF 12V', 'NGK MR9C-9N', 'Cek tahun/varian sebelum produksi.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'BeAT Street', 'matic', '10W-30 JASO MB', '0.65 L', '80/90-14', '90/90-14', 'MF 12V', 'NGK MR9C-9N', 'Cek tahun/varian sebelum produksi.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'Scoopy', 'matic', '10W-30 JASO MB', '0.65 L', '100/90-12', '110/90-12', 'MF 12V 5Ah', 'NGK MR9C-9N', 'Ukuran mengikuti generasi yang dirujuk.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'Genio', 'matic', '10W-30 JASO MB', '0.65 L', '80/90-14', '90/90-14', 'MF 12V', 'NGK MR9C-9N', 'Varian/tahun dapat berbeda.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'Vario 125', 'matic', '10W-30 JASO MB', '0.80 L', '90/80-14', '100/80-14', 'MF 12V', 'NGK MR9C-9N', 'Cek manual sesuai tahun.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'Vario 125 Street', 'matic', '10W-30 JASO MB', '0.80 L', '90/80-14', '100/80-14', 'MF 12V', 'NGK MR9C-9N', 'Model terbaru; verifikasi manual varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'Vario 160', 'matic', '10W-30 JASO MB', '0.80 L', '100/80-14', '120/70-14', 'MF 12V', 'NGK LMAR8L-9', 'Verifikasi tahun/varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'Vario Evo 160', 'matic', '10W-30 JASO MB', 'Sesuai manual', 'Sesuai varian', 'Sesuai varian', 'Sesuai varian', 'Sesuai manual', 'Model 2026; detail servis mengikuti manual resmi.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'Stylo 160', 'matic', '10W-30 JASO MB', '0.80 L', '110/90-12', '130/70-12', 'MF 12V', 'NGK LMAR8L-9', 'Verifikasi manual.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'PCX 160', 'matic', '10W-30 JASO MB', '0.80 L', '110/70-14', '130/70-13', 'MF 12V', 'NGK LMAR8L-9', 'Verifikasi tahun/varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'ADV 160', 'matic', '10W-30 JASO MB', '0.80 L', '110/80-14', '130/70-13', 'MF 12V', 'NGK LMAR8L-9', 'Verifikasi tahun/varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'Forza', 'matic', '10W-30 JASO MB', '1.20 L', '120/70-15', '140/70-14', 'MF 12V', 'NGK LMAR8A-9', 'Kapasitas dapat berbeda menurut generasi.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'Air Blade 125', 'matic', '10W-30 JASO MB', 'Sesuai manual', 'Sesuai varian', 'Sesuai varian', 'MF 12V', 'Sesuai manual', 'Pasar/varian Indonesia perlu diverifikasi.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'ADV 150', 'matic', '10W-30 JASO MB', '0.80 L', '110/80-14', '130/70-13', 'MF 12V', 'NGK LMAR8L-9', 'Model generasi sebelumnya.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'PCX 150', 'matic', '10W-30 JASO MB', '0.80 L', '100/80-14', '120/70-14', 'MF 12V', 'NGK LMAR8A-9', 'Model generasi sebelumnya.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'SH150i', 'matic', '10W-30 JASO MB', 'Sesuai manual', 'Sesuai varian', 'Sesuai varian', 'Sesuai varian', 'Sesuai manual', 'Bukan model utama lineup AHM saat ini.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'Zoomer-X', 'matic', '10W-30 JASO MB', 'Sesuai manual', 'Sesuai varian', 'Sesuai varian', 'Sesuai varian', 'Sesuai manual', 'Model lama/pasar tertentu.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'PCX Electric', 'matic', 'Tidak berlaku', 'Tidak menggunakan oli mesin', 'Sesuai varian', 'Sesuai varian', 'Baterai listrik', 'Tidak berlaku', 'Kendaraan listrik; kolom oli tidak berlaku.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'Supra X 125', 'manual', '10W-30 JASO MA', '0.70 L', '70/90-17', '80/90-17', '12V 3Ah', 'NGK CPR6EA-9', '4-speed rotary; verifikasi varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'Revo', 'manual', '10W-30 JASO MA', '0.70 L', '70/90-17', '80/90-17', 'MF 12V', 'NGK CPR6EA-9', 'Verifikasi tahun/varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'Revo X', 'manual', '10W-30 JASO MA', '0.70 L', '70/90-17', '80/90-17', 'MF 12V', 'NGK CPR6EA-9', 'Verifikasi tahun/varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'Supra GTR 150', 'manual', '10W-30 JASO MA', '1.10 L', '90/80-17', '120/70-17', 'MF 12V', 'NGK MR9C-9N', '6-speed; verifikasi manual.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'CT125', 'manual', '10W-30 JASO MA', '0.85 L', '80/90-17', '80/90-17', 'MF 12V', 'NGK CPR6EA-9', 'Motor trail-cub; verifikasi manual.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'Super Cub C125', 'manual', '10W-30 JASO MA', '0.85 L', '70/90-17', '80/90-17', 'MF 12V', 'NGK CPR6EA-9', 'Model premium cub.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'Astrea Grand', 'manual', '10W-30 JASO MA', 'Sesuai manual', 'Sesuai varian', 'Sesuai varian', 'Sesuai varian', 'Sesuai manual', 'Model lama; data perlu verifikasi manual.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'Karisma', 'manual', '10W-30 JASO MA', 'Sesuai manual', 'Sesuai varian', 'Sesuai varian', 'Sesuai varian', 'Sesuai manual', 'Model lama.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'Blade 125', 'manual', '10W-30 JASO MA', 'Sesuai manual', 'Sesuai varian', 'Sesuai varian', 'Sesuai varian', 'Sesuai manual', 'Model generasi sebelumnya.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'CS1', 'manual', '10W-30 JASO MA', 'Sesuai manual', 'Sesuai varian', 'Sesuai varian', 'Sesuai varian', 'Sesuai manual', 'Model lama.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'CB150R StreetFire', 'kopling', '10W-40 JASO MA2', '1.10 L', '100/80-17', '130/70-17', 'MF 12V 5Ah', 'NGK MR9C-9N', 'Verifikasi tahun/varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'CB150 Verza', 'kopling', '10W-40 JASO MA', '1.00 L', '80/100-17', '100/90-17', 'MF 12V', 'NGK CPR9EA-9', 'Verifikasi tahun/varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'CB150X', 'kopling', '10W-30/40 JASO MA2', '1.30 L', '100/80-17', '130/70-17', 'MF 12V', 'NGK MR9C-9N', 'Verifikasi manual.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'CRF150L', 'kopling', '10W-40 JASO MA2', '1.10 L', '90/90-21', '120/80-18', 'MF 12V', 'NGK CR8E', 'Dual-purpose.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'CBR150R', 'kopling', '10W-30/40 JASO MA2', '1.10 L', '100/80-17', '130/70-17', 'MF 12V', 'NGK MR9C-9N', 'Verifikasi generasi.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'CRF250L', 'kopling', '10W-30 JASO MA2', '1.45 L', '80/100-21', '120/80-18', 'MF 12V', 'NGK SIMR8A9', 'Kapasitas mengikuti manual generasi.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'CBR250RR', 'kopling', '10W-30 JASO MA2', '1.90 L', '110/70-17', '140/70-17', 'MF 12V', 'NGK SILMAR9C-9S', 'Verifikasi generasi.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'Rebel 500', 'kopling', '10W-40 JASO MA2', 'Sesuai manual', '130/90-16', '150/80-16', 'MF 12V', 'Sesuai manual', 'Big bike; gunakan manual resmi.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'CB500F', 'kopling', '10W-40 JASO MA2', 'Sesuai manual', '120/70-17', '160/60-17', 'MF 12V', 'Sesuai manual', 'Big bike; verifikasi manual.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Honda', 'CB650R', 'kopling', '10W-40 JASO MA2', 'Sesuai manual', '120/70-17', '180/55-17', 'MF 12V', 'Sesuai manual', 'Big bike; verifikasi manual.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'Mio M3 125', 'matic', '10W-30 JASO MB', '0.80 L berkala', '70/90-14', '80/90-14', 'YTZ4V/GTZ4V', 'CR6HSA', 'Total 0.84 L; berkala 0.80 L.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'Mio Gear 125', 'matic', '10W-30 JASO MB', '0.80 L', '80/80-14', '100/70-14', 'YTZ6V/YTZ4V', 'CR6HSA', 'Varian dapat berbeda.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'Gear 125', 'matic', '10W-30 JASO MB', '0.80 L', '80/80-14', '100/70-14', 'YTZ6V/YTZ4V', 'CR6HSA', 'Varian Standard/S berbeda.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'Gear Ultima 125', 'matic', '10W-30 JASO MB', '0.80 L', '110/70-12', '110/70-12', 'YTZ6V', 'CR6HSA', 'Hybrid.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'Fazzio Hybrid', 'matic', '10W-30 JASO MB', '0.80 L berkala', '110/70-12', '110/70-12', 'YTZ6V', 'CR6HSA', 'Total 0.84 L.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'Grand Filano', 'matic', '10W-30 JASO MB', '0.80 L berkala', '110/70-12', '110/70-12', 'YTZ6V', 'CR6HSA', 'Verifikasi varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'FreeGo 125', 'matic', '10W-30 JASO MB', '0.80 L berkala', '100/90-12', '110/90-12', 'YTZ4V/GTZ4V/NTZ4V', 'CR6HSA', 'Aki berbeda menurut varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'FreeGo S', 'matic', '10W-30 JASO MB', '0.80 L berkala', '100/90-12', '110/90-12', 'YTZ6V/varian', 'CR6HSA', 'Verifikasi tahun.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'X-Ride 125', 'matic', '10W-30 JASO MB', '0.80 L', '80/80-14', '100/70-14', 'YTZ4V', 'CR6HSA', 'Verifikasi tahun.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'NMAX 155', 'matic', '10W-40 JASO MB', '0.90 L berkala', '110/70-13', '130/70-13', 'YTZ6V/YTZ7V', 'CPR8EA-9', 'Varian Standard/S/Connected berbeda.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'NMAX Turbo', 'matic', '10W-40 JASO MB', '0.90 L', '110/70-13', '140/70-13', 'Sesuai varian', 'CPR8EA-9', 'YECVT; verifikasi varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'NMAX Turbo Tech Max', 'matic', '10W-40 JASO MB', '0.90 L', '110/70-13', '140/70-13', 'Sesuai varian', 'CPR8EA-9', 'YECVT; verifikasi manual.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'Aerox 155', 'matic', '10W-40 JASO MB', '0.90 L berkala', '110/80-14', '140/70-14', 'YTZ7V/NTZ6V', 'CPR8EA-9', 'Battery berbeda menurut varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'Aerox Alpha', 'matic', '10W-40 JASO MB', '0.90 L', '110/80-14', '140/70-14', 'Sesuai varian', 'CPR8EA-9', 'Turbo variant dapat berbeda.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'Aerox Alpha Turbo', 'matic', '10W-40 JASO MB', '1.00 L', '110/80-14', '140/70-14', 'Sesuai varian', 'CPR8EA-9', 'YECVT; verifikasi manual.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'Lexi 155', 'matic', '10W-40 JASO MB', '0.90 L', '90/90-14', '100/90-14', 'YTZ6V', 'CPR8EA-9', 'Verifikasi tahun/varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'Lexi LX 155', 'matic', '10W-40 JASO MB', '0.90 L', '90/90-14', '100/90-14', 'YTZ6V', 'CPR8EA-9', 'Verifikasi varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'XMAX 250', 'matic', '10W-40 JASO MB', '1.50 L', '120/70-15', '140/70-14', 'YTZ7S', 'LMAR8A-9', 'Verifikasi generasi.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'XMAX Connected', 'matic', '10W-40 JASO MB', '1.50 L', '120/70-15', '140/70-14', 'YTZ7S', 'LMAR8A-9', 'Verifikasi generasi.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'TMAX', 'matic', '10W-40 JASO MB', 'Sesuai manual', '120/70-15', '160/60-15', 'Sesuai manual', 'Sesuai manual', 'Maxi scooter; pasar terbatas.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'Jupiter Z1', 'manual', '10W-40 JASO MA', '0.80 L', '70/90-17', '80/90-17', 'YTZ4V', 'CR6HSA', 'Verifikasi tahun.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'Jupiter MX 135', 'manual', '10W-40 JASO MA', '0.95 L', '70/90-17', '100/70-17', 'MF 12V', 'CR8E', 'Model lama.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'MX King 150', 'manual', '10W-40 JASO MA', '1.00 L', '90/80-17', '120/70-17', 'GTZ4V/YTZ4V', 'CR8E', 'Verifikasi tahun.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'Vega Force', 'manual', '10W-40 JASO MA', '0.80 L', '70/90-17', '80/90-17', 'MF 12V', 'CR6HSA', 'Verifikasi tahun.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'F1ZR', 'manual', '2T', 'Sesuai manual', 'Sesuai varian', 'Sesuai varian', 'Sesuai varian', 'Sesuai manual', 'Motor 2T lama; oli mesin dan oli samping berbeda.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'V80', 'manual', '2T', 'Sesuai manual', 'Sesuai varian', 'Sesuai varian', 'Sesuai varian', 'Sesuai manual', 'Motor 2T lama.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'Jupiter MX King 150', 'manual', '10W-40 JASO MA', '1.00 L', '90/80-17', '120/70-17', 'GTZ4V/YTZ4V', 'CR8E', 'Nama pemasaran dapat berbeda menurut tahun.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'R15', 'kopling', '10W-40 JASO MA2', '0.85 L berkala', '100/80-17', '140/70-17', 'GTZ4V/YTZ4V', 'LMAR8A-9', 'Total 1.05 L; 0.95 L dengan filter.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'R15M', 'kopling', '10W-40 JASO MA2', '0.85 L berkala', '100/80-17', '140/70-17', 'YTZ6V', 'LMAR8A-9', 'Verifikasi varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'MT-15', 'kopling', '10W-40 JASO MA2', '0.85 L berkala', '110/70-17', '140/70-17', 'YTZ4V', 'MR8E-9', 'Total 1.05 L.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'Vixion', 'kopling', '10W-40 JASO MA2', '0.95 L', '90/80-17', '120/70-17', 'YTZ4V', 'CR8E', 'Verifikasi generasi.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'Vixion R', 'kopling', '10W-40 JASO MA2', '0.95 L', '90/80-17', '130/70-17', 'YTZ4V', 'CR8E', 'Verifikasi generasi.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'XSR 155', 'kopling', '10W-40 JASO MA2', '0.85 L', '110/70-17', '140/70-17', 'YTZ4V', 'MR8E-9', 'Verifikasi tahun.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'WR155R', 'kopling', '10W-40 JASO MA2', '0.85 L', '2.75-21', '4.10-18', 'YTZ4V', 'NGK MR8E-9', 'Dual-purpose.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'YZF-R25', 'kopling', '10W-40 JASO MA2', '2.40 L', '110/70-17', '140/70-17', 'YTZ7S', 'NGK CR9E', 'Verifikasi generasi.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'MT-25', 'kopling', '10W-40 JASO MA2', '2.40 L', '110/70-17', '140/70-17', 'YTZ7S', 'NGK CR9E', 'Verifikasi generasi.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'Tenere 700', 'kopling', '10W-40 JASO MA2', 'Sesuai manual', '90/90-21', '150/70-18', 'Sesuai manual', 'Sesuai manual', 'Adventure bike; pasar terbatas.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Yamaha', 'YZ250F', 'kopling', '10W-40 JASO MA2', 'Sesuai manual', '80/100-21', '100/90-19', 'Sesuai manual', 'Sesuai manual', 'Competition/off-road; servis wajib manual.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Suzuki', 'Nex II', 'matic', '10W-40 JASO MB', 'Sesuai manual', '80/90-14', '90/90-14', 'MF', 'Sesuai manual', 'Verifikasi tahun/varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Suzuki', 'Nex Crossover', 'matic', '10W-40 JASO MB', 'Sesuai manual', '80/90-14', '90/90-14', 'MF', 'Sesuai manual', 'CVT; spesifikasi resmi tersedia di Suzuki.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Suzuki', 'Address FI', 'matic', '10W-40 JASO MB', 'Sesuai manual', '80/90-14', '90/90-14', 'MF', 'Sesuai manual', 'Verifikasi tahun.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Suzuki', 'Burgman Street 125EX', 'matic', '10W-40 JASO MB', 'Sesuai manual', '90/90-12', '100/80-12', 'MF', 'Sesuai manual', 'Verifikasi manual Indonesia.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Suzuki', 'Avenis 125', 'matic', '10W-40 JASO MB', 'Sesuai manual', '90/90-12', '90/90-12', 'MF', 'Sesuai manual', 'Pasar/varian perlu diverifikasi.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Suzuki', 'Satria F150', 'kopling', '10W-40 JASO MA2', 'Sesuai manual', '70/90-17', '80/90-17', 'MF', 'Sesuai manual', '6-speed.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Suzuki', 'Satria Pro', 'kopling', '10W-40 JASO MA2', 'Sesuai manual', '70/90-17', '80/90-17', 'MF', 'Sesuai manual', 'Verifikasi varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Suzuki', 'GSX-R150', 'kopling', '10W-40 JASO MA2', 'Sesuai manual', '90/80-17', '130/70-17', 'MF', 'Sesuai manual', '6-speed.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Suzuki', 'GSX-S150', 'kopling', '10W-40 JASO MA2', 'Sesuai manual', '90/80-17', '130/70-17', 'MF', 'Sesuai manual', '6-speed.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Suzuki', 'V-Strom 250SX', 'kopling', '10W-40 JASO MA2', 'Sesuai manual', '100/90-19', '140/70-17', 'MF', 'Sesuai manual', 'Adventure; verifikasi manual.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Suzuki', 'GSX-8S', 'kopling', '10W-40 JASO MA2', 'Sesuai manual', '120/70-17', '180/55-17', 'MF', 'Sesuai manual', 'Big bike; verifikasi manual.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Suzuki', 'Hayabusa', 'kopling', '10W-40 JASO MA2', 'Sesuai manual', '120/70ZR17', '190/50ZR17', 'MF', 'Sesuai manual', 'Big bike; verifikasi manual.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Kawasaki', 'KLX150', 'kopling', '10W-40 JASO MA2', 'Sesuai manual', '2.75-21', '4.10-18', 'MF', 'Sesuai manual', 'Dual-purpose.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Kawasaki', 'KLX150SM', 'kopling', '10W-40 JASO MA2', 'Sesuai manual', '100/80-17', '120/70-17', 'MF', 'Sesuai manual', 'Supermoto.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Kawasaki', 'KLX230', 'kopling', '10W-40 JASO MA2', 'Sesuai manual', '2.75-21', '4.10-18', 'MF', 'Sesuai manual', 'Dual-purpose.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Kawasaki', 'W175', 'kopling', '10W-40 JASO MA2', 'Sesuai manual', '80/100-19', '100/90-16', 'MF', 'Sesuai manual', 'Verifikasi varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Kawasaki', 'Ninja 250', 'kopling', '10W-40 JASO MA2', 'Sesuai manual', '110/70-17', '140/70-17', 'MF', 'Sesuai manual', 'Verifikasi generasi.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Kawasaki', 'Ninja ZX-25R', 'kopling', '10W-40 JASO MA2', 'Sesuai manual', '110/70-17', '150/60-17', 'MF', 'Sesuai manual', '4-cylinder; verifikasi manual.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Kawasaki', 'Ninja ZX-4RR', 'kopling', '10W-40 JASO MA2', 'Sesuai manual', '120/70-17', '160/60-17', 'MF', 'Sesuai manual', '4-cylinder; verifikasi manual.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Kawasaki', 'Eliminator', 'kopling', '10W-40 JASO MA2', 'Sesuai manual', '130/70-18', '150/80-16', 'MF', 'Sesuai manual', 'Cruiser; verifikasi manual.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Vespa', 'LX 125 i-Get', 'matic', '5W-40/10W-40 sesuai manual', 'Sesuai manual', '110/70-11', '120/70-10', 'MF', 'Sesuai manual', 'Verifikasi tahun/varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Vespa', 'S 125 i-Get', 'matic', '5W-40/10W-40 sesuai manual', 'Sesuai manual', '110/70-11', '120/70-10', 'MF', 'Sesuai manual', 'Verifikasi tahun/varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Vespa', 'Primavera 150 i-Get', 'matic', '5W-40/10W-40 sesuai manual', 'Sesuai manual', '110/70-12', '120/70-12', 'MF', 'Sesuai manual', 'Verifikasi tahun/varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;
insert into motor_specs (brand, model, type, oli, volume_oli, ban_depan, ban_belakang, aki, busi, catatan) values ('Vespa', 'Sprint 150 i-Get', 'matic', '5W-40/10W-40 sesuai manual', 'Sesuai manual', '110/70-12', '120/70-12', 'MF', 'Sesuai manual', 'Verifikasi tahun/varian.') on conflict (brand, model) do update set type=excluded.type, oli=excluded.oli, volume_oli=excluded.volume_oli, ban_depan=excluded.ban_depan, ban_belakang=excluded.ban_belakang, aki=excluded.aki, busi=excluded.busi, catatan=excluded.catatan;

select count(*) as motor_specs_total from motor_specs;