-- seed_workshops_tambal_cuci_24.sql -- 24 data (12 tambal ban + 12 cuci motor) dari database_bengkel_surabaya_tambal_ban_cuci_motor.xlsx
-- Sumber: pencarian Google Maps/web 30 Sep 2026. Verifikasi ulang sebelum publikasi.
-- Jalankan di Supabase SQL Editor. Idempotent via ON CONFLICT (slug).

insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('Tambal Ban Tip Top Surabaya', 'tambal-ban-tip-top-surabaya', 'Jl. Ngagel Jaya Selatan, Ngagelrejo, Kec. Wonokromo, Surabaya, Jawa Timur 60245', 'Wonokromo', '07:00-21:30', array['Tambal ban','tambal tubeless','tip-top'], '+6285792534548', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=Tambal%20Ban%20Tip%20Top%20Surabaya&query_place_id=ChIJK_q5HLH71y0R1ukx4I7YXWw', 4.7) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('Tambal Ban Ganesha Tubeless', 'tambal-ban-ganesha-tubeless', 'Jl. Kaliwaron No.78, Mojo, Kec. Gubeng, Surabaya, Jawa Timur 60285', 'Gubeng', '08:00-20:00', array['Tambal ban','tubeless','tip-top'], '', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=Tambal%20Ban%20Ganesha%20Tubeless&query_place_id=ChIJE9SYF4f51y0RBL9hiXQh-XE', 4.7) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('Tambal Ban 24 jam', 'tambal-ban-24-jam', 'Jl. Kenjeran No.490, Kalijudan, Kec. Mulyorejo, Surabaya, Jawa Timur 60134', 'Mulyorejo', '24 jam', array['Tambal ban'], '', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=Tambal%20Ban%2024%20jam&query_place_id=ChIJ0faDdrL51y0RygR0Mf_KOv4', 4.2) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('Tambal Ban 24 Jam Pak Gatot', 'tambal-ban-24-jam-pak-gatot', 'Jl. Porong No.1c, Darmo, Kec. Wonokromo, Surabaya, Jawa Timur 60241', 'Wonokromo', '24 jam', array['Tambal ban','perbaikan ban motor'], '+6282396759520', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=Tambal%20Ban%2024%20Jam%20Pak%20Gatot&query_place_id=ChIJJ_j2b7371y0RuaXnAgxAwOk', 4.6) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('Tambal Ban Pak Muhammad', 'tambal-ban-pak-muhammad', 'PQ5W+WCM, Keputih, Sukolilo, Surabaya, Jawa Timur 60111', 'Sukolilo', '24 jam', array['Tambal ban','perbaikan ban motor'], '+6281324200988', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=Tambal%20Ban%20Pak%20Muhammad&query_place_id=ChIJVfjHmyr71y0RlPsXmgkXE-Y', 5.0) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('Tambal ban panggilan pak ronald 24 jam', 'tambal-ban-panggilan-pak-ronald-24-jam', 'Jl. Dharmawangsa No.97, Kertajaya, Kec. Gubeng, Surabaya, Jawa Timur 60282', 'Gubeng', '24 jam', array['Tambal ban panggilan','perbaikan ban'], '+6281263396589', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=Tambal%20ban%20panggilan%20pak%20ronald%2024%20jam&query_place_id=ChIJ0_fQbH_71y0RDi5XuuGcanw', 5.0) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('Tambal tip top tubelles (pak eko)', 'tambal-tip-top-tubelles-pak-eko', 'Jl. Raya Tandes Kidul, Raya, Kec. Tandes, Surabaya, Jawa Timur 60186', 'Tandes', '09:00-19:00', array['Tambal ban','tubeless','tip-top'], '+6285606510103', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=Tambal%20tip%20top%20tubelles%20pak%20eko&query_place_id=ChIJ7Vc3myT_1y0RruphLqsNtlU', 4.9) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('Tambal tiptop fadila surabaya', 'tambal-tiptop-fadila-surabaya', 'PMRC+RP8, Jl. Manukan Tama, Manukan Kulon, Kec. Tandes, Surabaya, Jawa Timur 60185', 'Tandes', '09:00-21:00', array['Tambal ban','tip-top','tubeless'], '+6281231149307', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=Tambal%20tiptop%20fadila%20surabaya&query_place_id=ChIJoRPseej_1y0R8mXJvoEtvBM', 4.9) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('Tambal Ban Cak Mad', 'tambal-ban-cak-mad', 'Jl. Raya Wonokromo No.8, Wonokromo, Kec. Wonokromo, Surabaya, Jawa Timur 60244', 'Wonokromo', '06:00-00:00', array['Tambal ban','perbaikan ban'], '+6285940367779', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=Tambal%20Ban%20Cak%20Mad&query_place_id=ChIJqTnILQD71y0REEe3Ov05FtM', 5.0) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('Tambal Ban Sukses', 'tambal-ban-sukses', 'Jl. Raya Rungkut Mejoyo No.22 / G-11, Kali Rungkut, Kec. Rungkut, Surabaya, Jawa Timur 60293', 'Rungkut', '08:00-17:00', array['Tambal ban','perbaikan ban'], '+6281330329657', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=Tambal%20Ban%20Sukses&query_place_id=ChIJ10ifY1X71y0RBKjl-9YG5hs', 4.6) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('Tambal ban TIP TOP-TUBELESS', 'tambal-ban-tip-top-tubeless', 'Jl. Keputih Tegal Timur No.100, Keputih, Kec. Sukolilo, Surabaya, Jawa Timur 60111', 'Sukolilo', '07:30-16:30', array['Tambal ban','tubeless','tip-top'], '+6285855773899', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=Tambal%20ban%20TIP%20TOP-TUBELESS&query_place_id=ChIJl3UOr3H61y0RA4MAfAFGJ34', 4.7) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('TAMBAL BAN MEGA JAYA 1', 'tambal-ban-mega-jaya-1', 'Jl. Manukan Lor I Perumnas, Manukan Kulon, Kec. Tandes, Surabaya, Jawa Timur 60185', 'Tandes', '08:30-23:00', array['Tambal ban','perbaikan ban'], '+6283122151497', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=TAMBAL%20BAN%20MEGA%20JAYA%201&query_place_id=ChIJN2BmnlH_1y0RBzCvvH0sfGA', 4.7) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('RIDER+ Motowash (Mitra GTWash)', 'rider-motowash-mitra-gtwash', 'Jl. Kalianyar No. 26-D, Kapasari, Kec. Genteng, Surabaya, Jawa Timur 60273', 'Genteng', '08:00-20:45', array['Cuci motor','motowash'], '+6282260060200', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=RIDER%2B%20Motowash%20Mitra%20GTWash&query_place_id=ChIJNQ6QLJL51y0RWglBpcamoIg', 4.9) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('Cuci Motor MARKAZ', 'cuci-motor-markaz', 'Depan PLN, Jl. Menur Pumpungan No.67a, Menur Pumpungan, Kec. Sukolilo, Surabaya, Jawa Timur 60118', 'Sukolilo', '08:00-22:00', array['Cuci motor','steam'], '+6285655613441', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=Cuci%20Motor%20MARKAZ&query_place_id=ChIJ0_jc4rf71y0RBVhwIoWb-e4', 4.8) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('CUCIAN MOTOR RAJA STEAM', 'cucian-motor-raja-steam', 'Jl. Raya Menur No.20, RT.007/RW.08, Airlangga, Kec. Gubeng, Surabaya, Jawa Timur 60286', 'Gubeng', '07:00-21:00', array['Cuci motor','steam'], '+6282276735553', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=CUCIAN%20MOTOR%20RAJA%20STEAM&query_place_id=ChIJGxH0EXX71y0RsQ7MXlIvxlA', 4.1) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('Cuci Motor Keep Fresh 17,rungkut mapan', 'cuci-motor-keep-fresh-17-rungkut-mapan', 'Jalan Raya Rungkut Mapan FB-8, Rungkut Tengah, Kec. Gn. Anyar, Surabaya, Jawa Timur 60293', 'Gunung Anyar', '07:30-16:00', array['Cuci motor','steam'], '', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=Cuci%20Motor%20Keep%20Fresh%2017%20Rungkut%20Mapan&query_place_id=ChIJubunG-371y0Rb-M2H_wb0bQ', 4.6) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('Cuci Motor Maju Mapan 5758', 'cuci-motor-maju-mapan-5758', 'Jl. Sawentar No.1 A, Pacar Keling, Kec. Tambaksari, Surabaya, Jawa Timur 60131', 'Tambaksari', '06:30-21:00', array['Cuci motor','steam'], '', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=Cuci%20Motor%20Maju%20Mapan%205758&query_place_id=ChIJkTrwmwP51y0R2hJW83fRLR8', 4.8) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('Cuci Motor Ali Babaw', 'cuci-motor-ali-babaw', 'Jl. Gebang Putih No.36-34, Gebang Putih, Kec. Sukolilo, Surabaya, Jawa Timur 60117', 'Sukolilo', '08:00-18:00', array['Cuci motor','steam'], '+6282131141875', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=Cuci%20Motor%20Ali%20Babaw&query_place_id=ChIJ4U1eQED61y0RVzoC5qInGOI', 4.6) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('Win Wash - Cuci & Coating Motor Keputih', 'win-wash-cuci-coating-motor-keputih', 'Jl. Keputih Tegal Timur No.86-A, Keputih, Sukolilo, Surabaya, Jawa Timur 60111', 'Sukolilo', '08:00-21:00', array['Cuci motor','coating'], '+6282262921985', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=Win%20Wash%20Cuci%20Coating%20Motor%20Keputih&query_place_id=ChIJkxbtUwD71y0Rwl_XFkfG7a8', 4.9) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('Cuci 24Jam Mobil & Motor Wak Djoyo', 'cuci-24jam-mobil-motor-wak-djoyo', 'Jl. Banjar Sugihan Baru No.17i, Banjar Sugihan, Tandes, Surabaya, Jawa Timur 60185', 'Tandes', '24 jam', array['Cuci motor','cuci mobil'], '+6281334035553', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=Cuci%2024Jam%20Mobil%20%26%20Motor%20Wak%20Djoyo&query_place_id=ChIJU8d6w2b-1y0R6T0ykMBV25E', 4.3) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('CUCI MOTOR HIDROLIK PERMATA(AIR PDAM)', 'cuci-motor-hidrolik-permata-air-pdam', 'Jl. Semolowaru Tengah I No.3, Semolowaru, Kec. Sukolilo, Surabaya, Jawa Timur 60119', 'Sukolilo', '08:00-20:00', array['Cuci motor','hidrolik'], '+6281239218710', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=CUCI%20MOTOR%20HIDROLIK%20PERMATA%20AIR%20PDAM&query_place_id=ChIJ9c6gTnH71y0RoB7t06NXe-I', 4.7) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('Cuci Motor Ranto', 'cuci-motor-ranto', 'Jl. Bibis Tama No.16, Manukan Wetan, Kec. Tandes, Surabaya, Jawa Timur 60185', 'Tandes', '08:00-20:00', array['Cuci motor','steam'], '+6285218066866', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=Cuci%20Motor%20Ranto&query_place_id=ChIJM2wQGxT_1y0RHsQw-aGoZJs', 4.4) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('CUCI MOTOR UBAYA', 'cuci-motor-ubaya', 'Jl. Rungkut Lor Gg. III, Kali Rungkut, Kec. Rungkut, Surabaya, Jawa Timur 60237', 'Rungkut', '08:00-21:00', array['Cuci motor','steam'], '', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=CUCI%20MOTOR%20UBAYA&query_place_id=ChIJraw589D71y0RRgH0mmFhua0', 4.7) on conflict (slug) do nothing;
insert into workshops (name, slug, address, kecamatan, jam_operasional, layanan, kontak, foto_url, maps_url, rating) values ('Cuci motor YD 19', 'cuci-motor-yd-19', 'PQ6F+666, Jl. Menur Pumpungan, Klampis Ngasem, Kec. Sukolilo, Surabaya, Jawa Timur 60117', 'Sukolilo', '24 jam', array['Cuci motor'], '+6287792980772', '/motor3.jpeg', 'https://www.google.com/maps/search/?api=1&query=Cuci%20motor%20YD%2019&query_place_id=ChIJFah5bQD71y0RdYRruLGPJHU', 5.0) on conflict (slug) do nothing;

-- verifikasi:
select count(*) as tambal_cuci_total from workshops where slug in ('cuci-motor-yd-19','cucian-motor-raja-steam','tambal-ban-sukses','tambal-ban-24-jam','cuci-motor-maju-mapan-5758','rider-motowash-mitra-gtwash','cuci-motor-markaz','tambal-ban-cak-mad','cuci-motor-ranto','tambal-ban-panggilan-pak-ronald-24-jam','tambal-ban-ganesha-tubeless','cuci-24jam-mobil-motor-wak-djoyo','tambal-ban-24-jam-pak-gatot','tambal-tiptop-fadila-surabaya','tambal-ban-tip-top-surabaya','tambal-ban-tip-top-tubeless','cuci-motor-ali-babaw','win-wash-cuci-coating-motor-keputih','cuci-motor-keep-fresh-17-rungkut-mapan','cuci-motor-ubaya','cuci-motor-hidrolik-permata-air-pdam','tambal-ban-mega-jaya-1','tambal-ban-pak-muhammad','tambal-tip-top-tubelles-pak-eko');