-- seed_problems_excel_52.sql -- 52 masalah dari database_masalah_motor_motorkita.xlsx
-- Jalankan di Supabase SQL Editor. Idempotent via ON CONFLICT (slug).

insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('motor-sulit-dinyalakan', 'Motor Sulit Dinyalakan', array['Starter berputar tapi mesin tidak hidup, atau mesin membutuhkan beberapa kali percobaan untuk menyala'], array['Aki lemah','busi kotor','suplai bahan bakar bermasalah'], array['Cek bensin dan aki','Coba starter kembali','Periksa busi','Jika tetap tidak menyala, bawa ke bengkel'], false, 'Mesin') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('motor-tidak-bisa-distarter', 'Motor Tidak Bisa Distarter', array['Starter elektrik tidak berputar saat tombol starter ditekan'], array['Aki lemah','sekring putus','tombol starter atau relay bermasalah'], array['Cek aki','Cek sekring','Coba kick starter jika tersedia','Periksa sistem starter'], false, 'Mesin') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('mesin-mati-mendadak', 'Mesin Mati Mendadak', array['Mesin tiba-tiba mati saat motor sedang digunakan'], array['Bensin habis','gangguan kelistrikan','suplai bahan bakar terganggu','atau mesin terlalu panas'], array['Menepi di tempat aman','Matikan kontak','Cek bensin','Tunggu mesin dingin','Jika berulang, hubungi bengkel'], true, 'Mesin') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('mesin-brebet', 'Mesin Brebet', array['Tarikan mesin tersendat atau tidak halus terutama saat akselerasi'], array['Busi kotor','filter udara kotor','bahan bakar bermasalah','atau sistem injeksi perlu diperiksa'], array['Kurangi akselerasi','Periksa busi','Periksa filter udara','Periksa sistem bahan bakar'], false, 'Mesin') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('mesin-tidak-bertenaga', 'Mesin Tidak Bertenaga', array['Akselerasi terasa berat dan motor sulit mencapai kecepatan seperti biasanya'], array['Filter udara kotor','busi bermasalah','suplai bahan bakar kurang optimal','atau masalah transmisi'], array['Cek filter udara','Periksa busi','Periksa bahan bakar','Periksa transmisi jika gejala tetap muncul'], false, 'Mesin') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('mesin-overheat', 'Mesin Overheat', array['Indikator temperatur tinggi atau mesin terasa sangat panas'], array['Coolant kurang','sistem pendinginan bermasalah','radiator kotor','atau sirkulasi pendingin terganggu'], array['Menepi','Matikan mesin','Tunggu mesin dingin','Jangan membuka radiator saat panas','Periksa sistem pendinginan'], true, 'Pendinginan') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('mesin-berbunyi-kasar', 'Mesin Berbunyi Kasar', array['Suara mesin terdengar lebih kasar, berisik, atau berbeda dari biasanya'], array['Oli kurang','kualitas oli tidak sesuai','atau komponen mesin mengalami keausan'], array['Matikan mesin jika suara sangat keras','Cek level oli','Jangan memaksa berkendara','Periksa ke bengkel'], true, 'Mesin') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('mesin-bergetar-berlebihan', 'Mesin Bergetar Berlebihan', array['Getaran mesin terasa jauh lebih kuat dari kondisi normal'], array['Pembakaran tidak normal','dudukan mesin','atau komponen mesin bermasalah'], array['Kurangi kecepatan','Menepi jika getaran kuat','Periksa sumber getaran','Bawa ke bengkel'], true, 'Mesin') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('keluar-asap-putih', 'Keluar Asap Putih', array['Asap putih keluar dari knalpot secara terus-menerus dan lebih tebal dari biasanya'], array['Oli masuk ke ruang bakar atau terdapat masalah internal mesin'], array['Hentikan penggunaan jika asap tebal','Cek level oli','Jangan memaksa berkendara','Periksa mesin'], true, 'Knalpot') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('keluar-asap-hitam', 'Keluar Asap Hitam', array['Asap hitam keluar dari knalpot terutama saat mesin digas'], array['Campuran bahan bakar terlalu kaya','filter udara kotor','atau sistem bahan bakar perlu diperiksa'], array['Periksa filter udara','Periksa sistem bahan bakar','Lakukan servis jika gejala berlanjut'], false, 'Knalpot') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('aki-lemah', 'Aki Lemah', array['Starter elektrik berputar lambat atau lampu menjadi redup'], array['Aki melemah','usia aki sudah lama','atau sistem pengisian bermasalah'], array['Cek kondisi aki','Cek terminal aki','Ukur tegangan jika tersedia','Ganti aki jika sudah rusak'], false, 'Kelistrikan') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('lampu-tidak-menyala', 'Lampu Tidak Menyala', array['Lampu depan tidak menyala saat motor digunakan'], array['Bohlam/LED','sekring','sakelar','kabel','atau sistem kelistrikan bermasalah'], array['Menepi jika berkendara malam','Cek sakelar','Cek sekring','Periksa lampu'], true, 'Kelistrikan') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('klakson-tidak-bunyi', 'Klakson Tidak Bunyi', array['Klakson tidak mengeluarkan suara saat tombol ditekan'], array['Aki lemah','sekring','tombol klakson','kabel','atau unit klakson bermasalah'], array['Cek aki','Cek sekring','Periksa tombol dan konektor','Periksa klakson'], false, 'Kelistrikan') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('starter-elektrik-tidak-berfungsi', 'Starter Elektrik Tidak Berfungsi', array['Tombol starter ditekan tetapi motor starter tidak bekerja'], array['Aki lemah','relay starter','sekring','switch pengaman','atau tombol starter bermasalah'], array['Cek aki','Cek sekring','Pastikan standar samping dalam posisi sesuai','Coba starter alternatif jika tersedia'], false, 'Kelistrikan') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('speedometer-mati', 'Speedometer Mati', array['Panel instrumen tidak menyala atau informasi kecepatan tidak tampil'], array['Sekring','konektor','kabel','atau sistem kelistrikan bermasalah'], array['Menepi jika indikator keselamatan tidak terbaca','Cek sekring','Periksa konektor','Bawa ke bengkel'], true, 'Kelistrikan') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('lampu-sein-tidak-berkedip', 'Lampu Sein Tidak Berkedip', array['Lampu sein menyala tidak normal atau tidak berkedip'], array['Relay sein','lampu','konektor','atau rangkaian kelistrikan bermasalah'], array['Cek lampu sein','Cek konektor','Periksa relay','Hindari berkendara jika sistem sein tidak dapat memberi sinyal dengan baik'], true, 'Kelistrikan') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('motor-matic-bergetar-saat-jalan', 'Motor Matic Bergetar Saat Jalan', array['Motor bergetar atau terasa bergetar saat mulai bergerak dari posisi diam'], array['Kampas ganda/kopling CVT kotor atau aus','atau permukaan komponen CVT bermasalah'], array['Kurangi akselerasi','Periksa CVT','Bersihkan atau ganti komponen sesuai hasil pemeriksaan'], false, 'CVT') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('tarikan-matic-berat', 'Tarikan Matic Berat', array['Motor matic terasa lambat berakselerasi atau membutuhkan gas lebih besar'], array['Roller aus','V-belt aus','CVT kotor','atau komponen transmisi perlu diperiksa'], array['Periksa CVT','Periksa roller','Periksa V-belt','Lakukan servis CVT'], false, 'CVT') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('suara-berisik-dari-cvt', 'Suara Berisik dari CVT', array['Terdengar suara kasar, dengung, atau bunyi tidak biasa dari area CVT'], array['Roller','V-belt','bearing','atau komponen CVT bermasalah'], array['Kurangi penggunaan','Hentikan jika suara sangat keras','Periksa CVT di bengkel'], true, 'CVT') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('v-belt-cvt-putus', 'V-Belt CVT Putus', array['Mesin hidup tetapi roda tidak bergerak setelah gas diberikan'], array['V-belt putus atau mengalami kerusakan berat'], array['Matikan mesin','Jangan memaksa gas','Dorong ke tempat aman','Hubungi bengkel'], true, 'CVT') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('motor-matic-menjerit-saat-akselerasi', 'Motor Matic Menjerit Saat Akselerasi', array['Putaran mesin tinggi tetapi laju motor tidak sebanding'], array['CVT atau kopling mengalami slip','atau komponen transmisi aus'], array['Kurangi penggunaan','Hindari akselerasi keras','Periksa CVT'], true, 'CVT') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('cvt-berbunyi-kasar', 'CVT Berbunyi Kasar', array['Suara kasar muncul dari rumah CVT terutama saat mesin digas'], array['Komponen CVT kotor','aus','atau bearing bermasalah'], array['Hentikan jika suara semakin keras','Periksa CVT','Jangan memaksa berkendara'], true, 'CVT') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('rem-kurang-pakem', 'Rem Kurang Pakem', array['Motor membutuhkan jarak lebih panjang untuk berhenti atau tuas rem terasa kurang efektif'], array['Kampas rem aus','minyak rem kurang/bermasalah','atau sistem rem perlu diservis'], array['Kurangi kecepatan','Jaga jarak','Periksa kampas rem','Periksa minyak rem','Jangan berkendara jika rem sangat lemah'], true, 'Rem') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('rem-berbunyi', 'Rem Berbunyi', array['Terdengar bunyi mencicit atau gesekan saat pengereman'], array['Kampas rem kotor/aus','cakram bermasalah','atau terdapat benda asing'], array['Kurangi kecepatan','Periksa kampas','Periksa cakram','Servis jika bunyi menetap'], true, 'Rem') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('tuas-rem-terasa-dalam', 'Tuas Rem Terasa Dalam', array['Tuas rem harus ditekan lebih dalam dari biasanya sebelum rem bekerja'], array['Kampas rem aus','udara dalam sistem hidrolik','atau masalah sistem rem'], array['Kurangi kecepatan','Jangan berkendara cepat','Periksa minyak rem','Bawa ke bengkel'], true, 'Rem') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('rem-terasa-macet', 'Rem Terasa Macet', array['Roda terasa tertahan atau tidak bebas setelah rem dilepas'], array['Kaliper','kampas','piston','atau mekanisme rem bermasalah'], array['Hentikan penggunaan','Jangan memaksa motor berjalan','Hubungi bengkel'], true, 'Rem') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('motor-menarik-ke-satu-sisi-saat-rem', 'Motor Menarik ke Satu Sisi Saat Rem', array['Motor terasa menarik ke kiri atau kanan ketika pengereman'], array['Rem bekerja tidak seimbang','kondisi ban','roda','atau komponen rem bermasalah'], array['Kurangi kecepatan','Hentikan motor di tempat aman','Periksa sistem rem dan roda'], true, 'Rem') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('ban-kempes', 'Ban Kempes', array['Tekanan ban sangat rendah dan motor terasa berat atau tidak stabil'], array['Kebocoran','ban bocor','pentil bermasalah','atau tekanan tidak sesuai'], array['Menepi','Jangan berkendara jauh','Isi angin jika memungkinkan','Perbaiki kebocoran'], true, 'Ban & Roda') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('ban-bocor', 'Ban Bocor', array['Angin ban keluar dan tekanan turun setelah terkena benda tajam atau tanpa sebab jelas'], array['Paku/benda tajam','pentil bocor','atau kerusakan ban'], array['Menepi','Jangan berkendara dengan ban kempes','Gunakan alat/tambal darurat jika sesuai','Bawa ke tukang ban'], true, 'Ban & Roda') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('ban-aus', 'Ban Aus', array['Alur ban sudah tipis atau indikator keausan sudah terlihat'], array['Usia pemakaian','jarak tempuh','tekanan ban tidak sesuai','atau pola pemakaian'], array['Periksa kedalaman alur','Ganti ban jika sudah aus','Hindari berkendara dalam kondisi licin'], true, 'Ban & Roda') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('motor-terasa-goyang', 'Motor Terasa Goyang', array['Setang atau roda terasa tidak stabil terutama pada kecepatan tertentu'], array['Tekanan ban','bearing roda','velg','keseimbangan roda','atau komponen kemudi bermasalah'], array['Kurangi kecepatan','Menepi jika goyangan kuat','Cek tekanan ban','Periksa roda dan kemudi'], true, 'Ban & Roda') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('ban-benjol', 'Ban Benjol', array['Terdapat benjolan pada dinding atau permukaan ban'], array['Struktur ban rusak akibat benturan atau kerusakan internal'], array['Jangan digunakan untuk perjalanan jauh','Ganti ban','Hindari kecepatan tinggi'], true, 'Ban & Roda') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('motor-kehabisan-bensin', 'Motor Kehabisan Bensin', array['Mesin mati dan indikator bahan bakar menunjukkan kondisi kosong'], array['Bahan bakar habis'], array['Menepi di tempat aman','Matikan kontak','Isi bahan bakar','Pastikan tidak ada kebocoran'], true, 'Bahan Bakar') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('motor-boros-bensin', 'Motor Boros Bensin', array['Jarak tempuh menjadi jauh lebih sedikit dibanding biasanya untuk jumlah bahan bakar yang sama'], array['Tekanan ban rendah','gaya berkendara','filter udara kotor','atau sistem bahan bakar perlu diperiksa'], array['Cek tekanan ban','Periksa filter udara','Hindari akselerasi berlebihan','Periksa sistem bahan bakar'], false, 'Bahan Bakar') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('motor-sulit-hidup-setelah-isi-bensin', 'Motor Sulit Hidup Setelah Isi Bensin', array['Mesin sulit menyala setelah pengisian bahan bakar'], array['Kualitas bahan bakar bermasalah atau sistem bahan bakar mengalami gangguan'], array['Jangan terus menerus menstarter','Tunggu beberapa saat','Periksa sistem bahan bakar','Hubungi bengkel jika tetap tidak hidup'], false, 'Bahan Bakar') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('tercium-bau-bensin', 'Tercium Bau Bensin', array['Bau bensin sangat kuat di sekitar motor'], array['Kebocoran tangki','selang','injektor/karburator','atau sambungan bahan bakar'], array['Matikan mesin','Jauhkan dari api/rokok','Jangan gunakan motor','Periksa kebocoran di bengkel'], true, 'Bahan Bakar') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('kopling-selip', 'Kopling Selip', array['Putaran mesin naik tetapi akselerasi tidak sebanding'], array['Kampas kopling aus','setelan kopling tidak tepat','atau oli tidak sesuai'], array['Kurangi penggunaan','Hindari akselerasi keras','Periksa setelan dan kampas kopling'], true, 'Kopling') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('gigi-sulit-dipindahkan', 'Gigi Sulit Dipindahkan', array['Perpindahan gigi terasa keras atau sulit masuk'], array['Setelan kopling','oli','kabel kopling','atau mekanisme transmisi bermasalah'], array['Cek level dan kondisi oli','Periksa setelan kopling','Jangan memaksa tuas gigi'], true, 'Transmisi') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('motor-susah-masuk-netral', 'Motor Susah Masuk Netral', array['Gigi sulit dipindahkan ke posisi netral terutama saat berhenti'], array['Setelan kopling','oli','atau mekanisme pemindah gigi'], array['Periksa setelan kopling','Periksa oli','Lakukan servis jika gejala berulang'], false, 'Transmisi') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('kopling-terasa-berat', 'Kopling Terasa Berat', array['Tuas kopling terasa jauh lebih berat saat ditekan'], array['Kabel kopling kering/rusak','setelan tidak tepat','atau mekanisme kopling bermasalah'], array['Periksa kabel','Lumasi jika sesuai','Periksa setelan','Ganti kabel jika rusak'], false, 'Kopling') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('rantai-terlalu-kendur', 'Rantai Terlalu Kendur', array['Rantai terlihat terlalu longgar atau berbunyi saat motor berjalan'], array['Setelan rantai berubah','rantai memanjang/aus','atau sprocket aus'], array['Kurangi kecepatan','Periksa kekencangan rantai','Setel sesuai manual','Ganti komponen jika aus'], true, 'Rantai') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('motor-terasa-memantul-berlebihan', 'Motor Terasa Memantul Berlebihan', array['Motor terasa memantul berlebihan setelah melewati jalan tidak rata'], array['Shock absorber aus atau bermasalah'], array['Kurangi kecepatan','Hindari beban berlebih','Periksa suspensi'], true, 'Suspensi') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('shockbreaker-bocor', 'Shockbreaker Bocor', array['Terlihat cairan/oli pada tabung shockbreaker'], array['Seal shock rusak atau komponen suspensi mengalami kebocoran'], array['Kurangi kecepatan','Periksa shockbreaker','Servis atau ganti komponen'], true, 'Suspensi') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('setang-terasa-berat', 'Setang Terasa Berat', array['Setang sulit digerakkan atau terasa berat saat berbelok'], array['Tekanan ban','bearing kemudi','atau komponen kemudi bermasalah'], array['Kurangi kecepatan','Periksa tekanan ban','Periksa bearing dan kemudi'], true, 'Suspensi') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('motor-terasa-oleng', 'Motor Terasa Oleng', array['Motor terasa tidak stabil saat menikung atau melewati permukaan tidak rata'], array['Suspensi','ban','roda','bearing','atau rangka perlu diperiksa'], array['Kurangi kecepatan','Hindari manuver mendadak','Periksa ban, roda, dan suspensi'], true, 'Suspensi') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('oli-mesin-berkurang-cepat', 'Oli Mesin Berkurang Cepat', array['Level oli turun dalam waktu singkat tanpa penggantian oli normal'], array['Kebocoran','oli terbakar','atau masalah internal mesin'], array['Cek level oli','Periksa kebocoran','Jangan gunakan jika oli sangat kurang','Bawa ke bengkel'], true, 'Oli & Pelumasan') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('terjadi-kebocoran-oli', 'Terjadi Kebocoran Oli', array['Terlihat tetesan atau genangan oli di bawah motor'], array['Seal','gasket','baut','atau komponen mesin mengalami kebocoran'], array['Matikan mesin jika kebocoran besar','Jangan berkendara jika oli terus keluar','Periksa di bengkel'], true, 'Oli & Pelumasan') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('oli-mesin-terlalu-kotor', 'Oli Mesin Terlalu Kotor', array['Warna dan kondisi oli sangat kotor atau sudah melewati interval penggantian'], array['Interval servis terlambat atau kondisi penggunaan berat'], array['Cek level oli','Ganti oli sesuai interval manual','Periksa kondisi mesin jika oli sangat kotor'], false, 'Oli & Pelumasan') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('indikator-oli-menyala', 'Indikator Oli Menyala', array['Lampu indikator oli menyala saat mesin hidup'], array['Level oli rendah atau sistem pelumasan/indikator mengalami masalah'], array['Menepi','Matikan mesin','Cek level oli','Jangan lanjutkan perjalanan jika indikator tetap menyala'], true, 'Oli & Pelumasan') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('knalpot-mengeluarkan-suara-tidak-normal', 'Knalpot Mengeluarkan Suara Tidak Normal', array['Suara knalpot lebih keras atau berbeda dari biasanya'], array['Knalpot bocor','sambungan longgar','atau komponen knalpot rusak'], array['Kurangi penggunaan','Periksa sambungan knalpot','Perbaiki kebocoran'], true, 'Knalpot') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('knalpot-bocor', 'Knalpot Bocor', array['Terdengar suara bocor atau gas buang keluar dari sambungan knalpot'], array['Gasket','sambungan','atau pipa knalpot rusak'], array['Jangan menyentuh knalpot saat panas','Periksa kebocoran','Servis knalpot'], true, 'Knalpot') on conflict (slug) do nothing;
insert into motor_problems (slug, title, gejala, penyebab, langkah, is_emergency, category) values ('bau-gas-buang-masuk-ke-area-pengendara', 'Bau Gas Buang Masuk ke Area Pengendara', array['Bau gas buang terasa kuat di sekitar pengendara'], array['Kebocoran knalpot atau posisi pembuangan bermasalah'], array['Hentikan penggunaan jika bau sangat kuat','Buka ventilasi/menjauh dari sumber','Periksa knalpot'], true, 'Knalpot') on conflict (slug) do nothing;

-- verifikasi:
select count(*) as masalah_excel_total from motor_problems where slug in ('motor-sulit-dinyalakan','motor-tidak-bisa-distarter','mesin-mati-mendadak','mesin-brebet','mesin-tidak-bertenaga','mesin-overheat','mesin-berbunyi-kasar','mesin-bergetar-berlebihan','keluar-asap-putih','keluar-asap-hitam','aki-lemah','lampu-tidak-menyala','klakson-tidak-bunyi','starter-elektrik-tidak-berfungsi','speedometer-mati','lampu-sein-tidak-berkedip','motor-matic-bergetar-saat-jalan','tarikan-matic-berat','suara-berisik-dari-cvt','v-belt-cvt-putus','motor-matic-menjerit-saat-akselerasi','cvt-berbunyi-kasar','rem-kurang-pakem','rem-berbunyi','tuas-rem-terasa-dalam','rem-terasa-macet','motor-menarik-ke-satu-sisi-saat-rem','ban-kempes','ban-bocor','ban-aus','motor-terasa-goyang','ban-benjol','motor-kehabisan-bensin','motor-boros-bensin','motor-sulit-hidup-setelah-isi-bensin','tercium-bau-bensin','kopling-selip','gigi-sulit-dipindahkan','motor-susah-masuk-netral','kopling-terasa-berat','rantai-terlalu-kendur','motor-terasa-memantul-berlebihan','shockbreaker-bocor','setang-terasa-berat','motor-terasa-oleng','oli-mesin-berkurang-cepat','terjadi-kebocoran-oli','oli-mesin-terlalu-kotor','indikator-oli-menyala','knalpot-mengeluarkan-suara-tidak-normal','knalpot-bocor','bau-gas-buang-masuk-ke-area-pengendara');